Usage:

# ./test-network-interconnect-tester.py --config=../topology.xml \
 --interface=analyzer.ge0 --interface=analyzer.xe0 \
 --interface=local.ge15 --interface=local.xe2 --interface=local.xe3 \
 --test-internal-loopback=true --test-analyzer=true

Output:

+------------------------------------------------------------------------------------------------+
| Port \ Run    |    1   |    2   |    3   |    4   |    5   |    6   |    7   |    8   |    9   |
+------------------------------------------------------------------------------------------------+
| NORM          |  98.70 |  76.19 |  50.00 |  50.00 |   5.00 |  50.00 |   5.00 |  10.00 |  76.19 |
|------------------------------------------------------------------------------------------------|
| analyzer.ge0  | 101.40 |  76.45 |  50.18 |  51.34 |   5.02 |  50.94 |   5.02 |  10.02 |  76.62 |
|------------------------------------------------------------------------------------------------|
| local.ge15    | 101.37 |  76.41 |  50.16 |  51.33 |   5.01 |  50.98 |   5.02 |  10.05 |  76.66 |
|------------------------------------------------------------------------------------------------|
| local.xe3     |  97.85 |  55.10 |  76.91 |  56.40 |  12.65 |  72.83 |  12.52 |  13.32 |  55.27 |
|------------------------------------------------------------------------------------------------|
| local.xe2     |  97.91 |  55.12 |  76.96 |  56.43 |  12.65 |  72.88 |  12.53 |  13.33 |  55.30 |
|------------------------------------------------------------------------------------------------|
| analyzer.xe0  | 101.37 |  76.41 |  50.16 |  51.32 |   5.01 |  50.92 |   5.02 |  10.02 |  76.59 |
+------------------------------------------------------------------------------------------------+

Yes there is a problem exposed in the output.
